steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'mecab:latest', './docker']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '-d', '--name', 'mecab_container', '-p', '8080:8080', 'mecab:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-T', 'mecab_container', 'pytest', '/app/test_api.py']

timeout: 1200s
options:
  logging: CLOUD_LOGGING_ONLY
