steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'mecab:latest', './docker']

  - name: 'docker/compose:1.29.2'
    args: ['-f', './docker/docker-compose.yml', 'up', '-d'] 

  - name: 'docker/compose:1.29.2'
    args: ['-f', './docker/docker-compose.yml', 'exec', '-T', 'backend', 'pytest', '/app/test_api.py']

timeout: 1200s 
options:
  logging: CLOUD_LOGGING_ONLY
