name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --file ./docker/Dockerfile --tag mecab:latest

    - name: Run Docker container
      run: |
        docker run -d -p 8080:8080 --name test_container mecab:latest
        sleep 10 # 等待容器啟動

    - name: Check Docker container logs
      run: docker logs test_container

    - name: Run API tests
      run: |
        pip install pytest requests
        pytest test_api.py
    
    - name: Stop and remove container
      run: |
        docker stop test_container
        docker rm test_container
